ci: softfail on sentry install

diff --git a/.github/workflows/build_branch.yaml b/.github/workflows/build_branch.yaml
--- a/.github/workflows/build_branch.yaml
+++ b/.github/workflows/build_branch.yaml
@@ -223,7 +223,7 @@ jobs:
 ############################################
       - name: Install Sentry
         if: ${{ github.event.inputs.useCache == 'false' || steps.archive.outputs.cache-hit != 'true' }}
-        run: curl -sL https://sentry.io/get-cli/ | bash
+        run: curl -sL https://sentry.io/get-cli/ | bash || echo 'Failed to install sentry, it might already be installed'
       - name: Upload dSYM files to Sentry
         if: ${{ github.event.inputs.useCache == 'false' || steps.archive.outputs.cache-hit != 'true' }}
         run: sentry-cli upload-dif --org withfig --project macos-app --derived-data || echo "Sentry did not upload dSYM"
